
name: Tests
on: [push]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        ./unit_test.sh
        
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt install g++ python3 python3-pip python3-dev
        pip install meson pytest .

    - name: Compile
      run: |
        ./build.sh

    - name: Run program
      run: |
        ./test/test.sh    

    - name: Test outputs
      run: |
        python3 -m pytest --exitfirst --verbose