
name: Tests
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
  
    - name: Setup
      run: |
        sudo apt install g++ python3 python3-pip
        pip install pytest

    - name: Compile
      run: |
        g++ src/fn5.cpp -Isrc -std=c++20 -w -pthread -O3 -o fn5

    - name: Run program
      run: |
        ./test/test.sh    

    - name: Test outputs
      run: |
        python3 -m pytest --exitfirst --verbose