
name: Tests
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
  
    - name: Setup
      run: |
        sudo apt install g++ python3 python3-pip
        pip install pytest

    - name: Compile
      run: |
        ./build.sh

    - name: Run program
      run: |
        ./test/test.sh    

    - name: Test outputs
      run: |
        python3 -m pytest --exitfirst --verbose
      
    - name: Run unit tests
      run: |
        ./unit_test.sh